export const DRAG = {
    START: 'DRAG_START',
    END: 'DRAG_END'
}
export const DESIGNER = {
    ACTIVATE: 'DESIGNER_ACTIVATE',
    PROP_CHANGE: 'DESIGNER_PROP_CHANGE',
    DOUBLE_CLICK: 'DESIGNER_DOUBLE_CLICK',
    FOCUS: 'DESIGNER_FOCUS'
}
